server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb+srv://sergey:vashenko@cluster0-zdqsh.mongodb.net
      database: test-test-test
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 60000

